# Generated by Django 2.0.10 on 2019-02-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=250)),
                ('part_description', models.CharField(max_length=250, null=True)),
                ('quantity', models.IntegerField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('need_by_date', models.DateTimeField(null=True)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('status', models.BooleanField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Part_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_location', models.CharField(max_length=250, null=True)),
                ('purchase_price', models.CharField(max_length=50, null=True)),
                ('date_of_purchase', models.DateTimeField(null=True)),
                ('after_comments', models.CharField(max_length=250, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
            ],
        ),
    ]
