# Generated by Django 2.0.10 on 2019-01-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('months', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('materials', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('date_completed', models.DateTimeField()),
                ('current_mileage', models.IntegerField()),
                ('next_due_date', models.DateTimeField()),
                ('next_due_mile', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=250)),
                ('part_description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('need_by_date', models.DateTimeField()),
                ('comments', models.CharField(max_length=250)),
                ('purchase_location', models.CharField(max_length=250)),
                ('purchase_price', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateTimeField()),
                ('after_comments', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Part_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vehicle'),
        ),
    ]
