# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('months', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('materials', models.CharField(max_length=250)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('date_completed', models.CharField(max_length=100)),
                ('next_due_date', models.CharField(max_length=100)),
                ('next_due_mile', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('driveable', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('check_in', models.IntegerField()),
                ('vehicle_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vehicle'),
        ),
    ]
