# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=250)),
                ('date_requested', models.CharField(max_length=50)),
                ('need_by_date', models.CharField(max_length=50)),
                ('purchase_location', models.CharField(max_length=250)),
                ('purchase_price', models.CharField(max_length=50)),
                ('date_of_purchase', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maintenance')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vehicle')),
            ],
        ),
    ]
