# Generated by Django 2.0.10 on 2019-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='after_comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_of_purchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='need_by_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='purchase_location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='purchase_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
