# Generated by Django 2.0.10 on 2019-02-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190130_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='after_comments',
        ),
        migrations.RemoveField(
            model_name='part',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='part',
            name='purchase_location',
        ),
        migrations.RemoveField(
            model_name='part',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='part_history',
            name='after_comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='part_history',
            name='date_of_purchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='part_history',
            name='part',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part_history',
            name='purchase_location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='part_history',
            name='purchase_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
