# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='active',
        ),
    ]
