# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_vehicle_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_history',
            name='date_completed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenance_history',
            name='next_due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_of_purchase',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='need_by_date',
            field=models.DateTimeField(),
        ),
    ]
