# Generated by Django 2.0.10 on 2019-02-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='phone',
        ),
    ]
