# Generated by Django 2.1.5 on 2019-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190122_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='maintenance',
            field=models.ForeignKey(on_delete=None, to='app.Maintenance'),
        ),
    ]
