# Generated by Django 2.1.5 on 2019-01-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190123_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driveable',
        ),
    ]
