# Generated by Django 2.0.10 on 2019-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190205_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='materials',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
