# Generated by Django 2.1.5 on 2019-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190123_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='action',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='item',
            new_name='name',
        ),
    ]
