# Generated by Django 2.0.10 on 2019-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190210_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
