# Generated by Django 2.0.10 on 2019-02-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190210_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='maintenance_history',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='part',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='part_history',
            name='part',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Maintenance_History',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Part_History',
        ),
    ]
