# Generated by Django 2.1.5 on 2019-01-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190126_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_history',
            name='current_mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
