# Generated by Django 2.1.5 on 2019-01-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_maintenance_history_current_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_location', models.CharField(max_length=250)),
                ('purchase_price', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateTimeField()),
                ('comments', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='part',
            old_name='purchase_location',
            new_name='part_description',
        ),
        migrations.RemoveField(
            model_name='part',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='part',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='status',
        ),
        migrations.AddField(
            model_name='part_history',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Part'),
        ),
    ]
