# Generated by Django 2.1.5 on 2019-01-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190127_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='part',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maintenance'),
        ),
    ]
