# Generated by Django 2.1.5 on 2019-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190128_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
