# Generated by Django 2.0.10 on 2019-03-04 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tankSize', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('driveWheels', models.CharField(blank=True, max_length=100, null=True)),
                ('mpg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_creation', models.DateField(auto_now_add=True)),
                ('mileage_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
