# Generated by Django 2.0.10 on 2019-03-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenance_History',
            new_name='Maintenance_Record',
        ),
    ]
