# Generated by Django 2.0.10 on 2019-02-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oilType', models.CharField(max_length=200)),
                ('oilBrand', models.CharField(max_length=200)),
                ('oilQuantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oilUnit', models.CharField(max_length=200)),
                ('filterSize', models.CharField(max_length=200)),
                ('filterBrand', models.CharField(max_length=200)),
                ('drnBltSize', models.CharField(max_length=200)),
                ('drnBltWasherType', models.CharField(max_length=200)),
                ('drnBltWasherSize', models.CharField(max_length=200)),
                ('gloves', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
