# Generated by Django 2.0.10 on 2019-03-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20190221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='months',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
